version: '3.8'

services:
  app:
    image: app:latest
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - STORAGE_MODE=postgres
      - DATABASE_URL=postgres://postgres:12345678@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: